language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - nightly

env:
  global:
  - secure: "<encrypted MYPYPI_USER=username>"

matrix:
  allow_failures:
    - python: nightly
  include:
    - python: 3.6
      dist: xenial
      sudo: required

stages:
  - build
  - test
  - name: deploy
    if: branch = master

before_install:
  - pip install poetry

install:

script:

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - shenderson@mozilla.com
    on_success: never
    on_failure: always
